version: '3'

networks:
  api-gateway-net:
  profiles-net:

services:
  api-gateway:
    env_file:
      - .env-api-gateway
    image: bartoszmajkowski/auto-bids:api-gateway
    ports:
      - "0.0.0.0:4000:4000"
    networks:
      - api-gateway-net
      - profiles-net

  profiles:
    env_file:
      - .env-profiles
    image: bartoszmajkowski/auto-bids:profiles
    ports:
      - "0.0.0.0:4100:4100"
    networks:
      - api-gateway-net
      - profiles-net

