apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: autobidscloud/auto-bids:chat
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4500
          env:
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: DB
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: DB_NAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: PORT
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: GIN_MODE
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
